- name: Copy SystemD
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: Start Service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    state: restarted
    enabled: yes
  daemon_reload: yes